In [1]:
import tensorflow as tf

input = tf.constant([1,-1,0,-1,2,1,0,2,-2], shape=[1,3,3,1], dtype=tf.float32)
filter_weight = tf.constant([1,-1,0,2], shape=[2,2,1,1], dtype=tf.float32)
biases = tf.constant([1], dtype=tf.float32)

with tf.Session() as sess:
    conv = tf.nn.conv2d(input, filter_weight, strides=[1, 1, 1, 1], padding='VALID')
    output = tf.nn.relu(tf.nn.bias_add(conv, biases))
    print sess.run(output)

[[[[7.]
   [2.]]

  [[2.]
   [0.]]]]


In [2]:
with tf.Session() as sess:
    conv = tf.nn.conv2d(input, filter_weight, strides=[1, 1, 1, 1], padding='SAME')
    output = tf.nn.relu(tf.nn.bias_add(conv, biases))
    print sess.run(output)

[[[[7.]
   [2.]
   [1.]]

  [[2.]
   [0.]
   [2.]]

  [[0.]
   [5.]
   [0.]]]]


In [3]:
with tf.Session() as sess:
    conv = tf.nn.conv2d(input, filter_weight, strides=[1, 2, 2, 1], padding='SAME')
    output = tf.nn.relu(tf.nn.bias_add(conv, biases))
    print sess.run(output)

[[[[7.]
   [1.]]

  [[0.]
   [0.]]]]
